#!/usr/bin/env php
<?php

use Tempest\Console\ConsoleApplication;

require_once getcwd() . '/vendor/autoload.php';
require_once getcwd() . '/bootstrap/tempest_internal_storage.php';

ConsoleApplication::boot(internalStorage: tempest_internal_storage())->run();

exit();
