<?php

declare(strict_types=1);

namespace Tests\Feature;

use Tempest\Http\Status;

test('a vault original asset is not safe to delete and is regenerable only by re-fetching upstream', function (): void {
    [$headers, $stashId, $mediaItemId] = $this->bootstrapFakeDownloadStash('guidance-original');

    $this->http->post('/api/v1/commands', [
        'type' => 'item.download',
        'options' => ['media_item_id' => $mediaItemId, 'stash_id' => $stashId],
    ], headers: $headers)->assertStatus(Status::CREATED);
    $this->processAllJobs();

    $response = $this->http->get("/api/v1/items/{$mediaItemId}/assets", headers: $headers)->assertOk();

    $original = array_values(array_filter(
        $response->body['assets'],
        static fn (array $asset): bool => $asset['role'] === 'vault_original',
    ))[0];

    expect($original['generated_by'])->toBeNull()
        ->and($original['can_regenerate'])->toBeTrue()
        ->and($original['safe_to_delete'])->toBeFalse();
});

test('a broadcast hardlink asset is generated by its broadcast and safe to delete', function (): void {
    [$headers, $stashId, $mediaItemId, $broadcastId] = $this->bootstrapFakeDownloadBroadcast('guidance-hardlink');

    $this->http->post('/api/v1/commands', [
        'type' => 'item.download',
        'options' => ['media_item_id' => $mediaItemId, 'stash_id' => $stashId],
    ], headers: $headers)->assertStatus(Status::CREATED);
    $this->processAllJobs();

    $broadcast = $this->http->get("/api/v1/broadcasts/{$broadcastId}", headers: $headers)->assertOk();
    $broadcastName = $broadcast->body['broadcast']['name'];

    $this->http->post('/api/v1/commands', [
        'type' => 'broadcast.rebuild',
        'options' => ['broadcast_id' => $broadcastId],
    ], headers: $headers)->assertStatus(Status::CREATED);
    $this->processAllJobs();

    $response = $this->http->get("/api/v1/items/{$mediaItemId}/assets", headers: $headers)->assertOk();

    $hardlinks = array_values(array_filter(
        $response->body['assets'],
        static fn (array $asset): bool => $asset['role'] === 'hardlink',
    ));

    expect($hardlinks)->not->toBeEmpty();

    foreach ($hardlinks as $hardlink) {
        expect($hardlink['generated_by'])->toBe($broadcastName)
            ->and($hardlink['can_regenerate'])->toBeTrue()
            ->and($hardlink['safe_to_delete'])->toBeTrue();
    }
});
