<?php

declare(strict_types=1);

namespace App\Broadcasts;

use App\Broadcasts\Podcasts\PodcastTokenService;
use App\Http\Middleware\RequireAuthMiddleware;
use App\Http\Routing\AllowApiClients;
use SensitiveParameter;
use Tempest\Http\ContentType;
use Tempest\Http\Response;
use Tempest\Http\Responses\NotFound;
use Tempest\Http\Responses\Ok;
use Tempest\Router\Get;

/**
 * Public, unauthenticated podcast feed surface.
 *
 * Podcast feeds are distributed by URL, not by login: anyone holding the path
 * token can read the feed. The token is the only credential, so an unknown,
 * revoked, or rotated-old token must be indistinguishable from a podcast that
 * was never created. This controller deliberately sits outside
 * {@see \App\Http\Middleware\RequireAuthMiddleware} and only serves the
 * `feed.xml` generated by `broadcast.rebuild` — it never rebuilds on demand.
 */
#[AllowApiClients]
final readonly class PodcastFeedController
{
    public function __construct(
        private PodcastTokenService $tokens,
        private BroadcastPathBuilder $paths,
    ) {
    }

    #[Get('/b/{broadcastToken}/feed.xml', without: [RequireAuthMiddleware::class])]
    public function feed(#[SensitiveParameter] string $broadcastToken): Response
    {
        $broadcast = $this->tokens->findPodcastBroadcastByFeedToken($broadcastToken);

        if ($broadcast === null) {
            return $this->notRevealed();
        }

        $feedPath = $this->paths->broadcastFile($broadcast, 'feed.xml');

        if (! is_file($feedPath) || ! is_readable($feedPath)) {
            return $this->notRevealed();
        }

        $xml = @file_get_contents($feedPath);

        if ($xml === false) {
            return $this->notRevealed();
        }

        return (new Ok($xml))
            ->addHeader(ContentType::HEADER, 'application/rss+xml; charset=utf-8');
    }

    /**
     * A single non-revealing response for every failure mode (unknown token,
     * revoked token, non-podcast broadcast, feed not yet generated). It carries
     * no broadcast identity, token, or filesystem path.
     */
    private function notRevealed(): NotFound
    {
        return new NotFound();
    }
}
